project_id = "clmaqdnphbndvmmqvpff"

[functions.validation-orchestrator]
verify_jwt = false

[functions.answer-engine]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.import-business-website]
verify_jwt = false

[functions.search-gmb-profile]
verify_jwt = false

[functions.alex-renovation]
verify_jwt = false

[functions.business-lookup]
verify_jwt = false