-- Rollback for drizzle/migrations/0002 (restores the previous always-true policies; re-opens the holes, use only in emergency)
ALTER POLICY "Users manage own business assets" ON public.business_assets TO authenticated USING (true) WITH CHECK (true);
ALTER POLICY "Users manage own business entities" ON public.business_entities TO authenticated USING (true) WITH CHECK (true);
ALTER POLICY "Users manage own import jobs" ON public.business_import_jobs TO authenticated USING (true) WITH CHECK (true);
ALTER POLICY "Users manage own business locations" ON public.business_locations TO authenticated USING (true) WITH CHECK (true);
ALTER POLICY "Users manage own business services" ON public.business_services TO authenticated USING (true) WITH CHECK (true);
ALTER POLICY "Users manage own completion events" ON public.profile_completion_events TO authenticated USING (true) WITH CHECK (true);
ALTER POLICY atos_public_update_self ON public.ai_trust_onboarding_sessions TO public USING (true) WITH CHECK (true);
ALTER POLICY "Public update steps" ON public.alex_score_reveal_steps TO public USING (true);
ALTER POLICY "Anyone can manage analyses" ON public.alex_visual_analyses TO public USING (true) WITH CHECK (true);
ALTER POLICY "Anyone can manage projections" ON public.alex_visual_projections TO public USING (true) WITH CHECK (true);
ALTER POLICY "Anyone can update voice sessions" ON public.alex_voice_sessions TO public USING (true);
ALTER POLICY "Anyone can manage consents" ON public.contractor_import_consents TO anon, authenticated USING (true) WITH CHECK (true);
ALTER POLICY import_scores_update_all ON public.contractor_import_scores TO public USING (true);
ALTER POLICY "Anyone can manage script events" ON public.contractor_import_script_events TO anon, authenticated USING (true) WITH CHECK (true);
ALTER POLICY "Anon can manage by conversation_id" ON public.conversation_activity_logs TO anon USING (true) WITH CHECK (true);
ALTER POLICY "Anyone can update votes" ON public.design_votes TO anon, authenticated USING (true) WITH CHECK (true);
ALTER POLICY "Anyone can update profile fields" ON public.entrepreneur_profile_fields TO anon, authenticated USING (true) WITH CHECK (true);
ALTER POLICY "Authenticated users can reserve spots" ON public.founder_spots TO authenticated USING (true) WITH CHECK (true);
ALTER POLICY "Authenticated users can update recruitment leads" ON public.recruitment_leads TO authenticated USING (true);
ALTER POLICY "Anyone can update inputs" ON public.self_serve_goal_plan_inputs TO public USING (true);
ALTER POLICY "Anyone can update sessions" ON public.self_serve_goal_plan_sessions TO public USING (true);
ALTER POLICY auth_update_verification_failures ON public.verification_failures TO authenticated USING (true);
ALTER POLICY auth_update_verification_runs ON public.verification_runs TO authenticated USING (true);
ALTER POLICY auth_update_verification_steps ON public.verification_steps TO authenticated USING (true);
ALTER POLICY "Anyone can update their own session" ON public.lead_funnel_sessions TO anon, authenticated USING (true) WITH CHECK (true);
GRANT UPDATE ON public.lead_funnel_sessions TO anon, authenticated;
ALTER POLICY demo_isr_update_any ON public.demo_contractor_plan_tests TO public USING (true) WITH CHECK (true);
GRANT UPDATE ON public.demo_contractor_plan_tests TO anon, authenticated;
