-- service_role has BYPASSRLS; these always-true policies are redundant and flagged as tautologies.
DROP POLICY "Service role full access acquisition events" ON public.acquisition_events;
DROP POLICY "Service role manages places budget" ON public.places_external_call_budget;
DROP POLICY "Service role manages enrichment circuit" ON public.external_enrichment_circuit;
DROP POLICY "Service role manages enrichment budget" ON public.external_enrichment_budget;
DROP POLICY "Service role manages dataforseo attempts" ON public.dataforseo_enrichment_attempts;
DROP POLICY "service_role manages auth role intents" ON public.auth_role_intents;
DROP POLICY "Service role manages intake keys" ON public.project_intake_keys;
DROP POLICY "internal job tokens are service-only" ON public.internal_job_tokens;
DROP POLICY "Service role manages discovery runs" ON public.acquisition_discovery_runs;
DROP POLICY "Service role manages geo pages" ON public.aipp_geo_pages;
DROP POLICY "Service oee" ON public.outreach_email_events;
DROP POLICY "Service writes agent_outreach" ON public.agent_outreach_messages;
DROP POLICY "Service role manages media assets" ON public.media_assets;
DROP POLICY "Service manages cptr" ON public.critical_path_test_runs;
DROP POLICY "Service role manages send queue" ON public.sniper_send_queue;
DROP POLICY "Service role manages contractor DNA" ON public.contractor_dna_profiles;
DROP POLICY "Service role access growth_engine_metrics" ON public.growth_engine_metrics;
DROP POLICY "Service role manages rag documents" ON public.rag_documents;
DROP POLICY "Service writes growth_outbound_messages" ON public.growth_outbound_messages;
DROP POLICY "Service role can read score reveal sessions" ON public.alex_score_reveal_sessions;
DROP POLICY "Service role can update score reveal sessions" ON public.alex_score_reveal_sessions;
DROP POLICY "service role manages oscr" ON public.official_site_crawl_runs;
DROP POLICY "service role manages osee" ON public.official_site_enrichment_evidence;
DROP POLICY "Service role manages extractions" ON public.property_ai_extractions;
DROP POLICY "Service role manages review dimension scores" ON public.contractor_review_dimension_scores;
DROP POLICY "Service role full access on pages_queue" ON public.pages_queue;
DROP POLICY "Service e2e" ON public.acq_e2e_test_runs;
DROP POLICY service_insert_risk_scores ON public.market_lead_risk_scores;
DROP POLICY "Service writes growth_agent_logs" ON public.growth_agent_logs;
DROP POLICY contractor_entities_service_write ON public.contractor_entities;
DROP POLICY "Service role manages query logs" ON public.rag_queries_log;
DROP POLICY "Service role can manage message events" ON public.message_events;
DROP POLICY "Service role manages rag chunks" ON public.rag_chunks;
DROP POLICY service_insert_actions ON public.market_next_best_actions;
DROP POLICY "Service role manages performance metrics" ON public.contractor_performance_metrics;
DROP POLICY "Service can manage territory assignments" ON public.territory_assignments;
DROP POLICY "Service role manages master records" ON public.property_master_records;
DROP POLICY "Service role manages agent memory" ON public.agent_memory;
DROP POLICY "service writes outreach_repair_actions" ON public.outreach_repair_actions;
DROP POLICY "Service role manages unpro_stripe_webhook_events" ON public.unpro_stripe_webhook_events;
DROP POLICY "Service role manages unpro_payment_activation_audit" ON public.unpro_payment_activation_audit;
DROP POLICY property_graph_service_all ON public.property_graph;
DROP POLICY "Service role writes outcomes" ON public.platform_operation_outcomes;
DROP POLICY "Service cta" ON public.cta_links;
DROP POLICY "Service role manages ingestion jobs" ON public.ingestion_jobs;
DROP POLICY "Service writes quotas" ON public.activation_quotas;
DROP POLICY "Service ose" ON public.outreach_sms_events;
DROP POLICY "Service role manages subscriptions" ON public.subscription_accounts;
DROP POLICY engagement_service_all ON public.pipeline_engagement_events;
DROP POLICY "Service role manages tracking links" ON public.acquisition_tracking_links;
DROP POLICY "service role full access" ON public.auth_otp_attempts;
DROP POLICY "Service role manages agent logs" ON public.agent_logs;
DROP POLICY "Service role manages embeddings" ON public.contractor_embeddings;
DROP POLICY "Service role access growth_events" ON public.growth_events;
DROP POLICY "Service writes cpms" ON public.critical_path_metrics_snapshot;
DROP POLICY "Service role insert war_logs" ON public.war_prospect_logs;
DROP POLICY "Service role manages email cta audit" ON public.email_cta_audit_findings;
DROP POLICY "Service role full access enriched profiles" ON public.contractor_enriched_profiles;
DROP POLICY "Service role manages agent metrics" ON public.agent_metrics;
DROP POLICY "Service role manages message variants" ON public.sniper_message_variants;
DROP POLICY "Service role can manage click events" ON public.click_events;
DROP POLICY "Service role manages usage" ON public.design_usage;
DROP POLICY "Service role manages document chunks" ON public.document_chunks;
DROP POLICY "Service manages contractor onboarding messages" ON public.contractor_onboarding_messages;
DROP POLICY "Service role full access voice_agent_mappings" ON public.voice_agent_mappings;
DROP POLICY "Service role manages merge candidates" ON public.property_merge_candidates;
DROP POLICY "Service role manages match evaluations" ON public.match_evaluations;
DROP POLICY "Service writes first dollar milestones" ON public.first_dollar_milestones;
DROP POLICY "Service gate" ON public.outreach_autopilot_gate;
DROP POLICY "Service role full access voice_configs" ON public.voice_configs;
DROP POLICY service_insert_feedback ON public.market_feedback_events;
DROP POLICY "Service role manages conversation memory" ON public.conversation_memory;
DROP POLICY "Service role manages pipeline events" ON public.acquisition_pipeline_events;
DROP POLICY "Service role manages activation flow events" ON public.activation_flow_events;
DROP POLICY "Service role manages project matches" ON public.project_matches;
DROP POLICY "Service role can read outreach page events" ON public.outreach_page_events;
DROP POLICY "Service role full access war_campaigns" ON public.war_campaigns;
DROP POLICY "Service can manage subscriptions" ON public.contractor_subscriptions;
DROP POLICY "Service role manages public scores" ON public.contractor_public_scores;
DROP POLICY "Service role manages agent registry" ON public.agent_registry;
DROP POLICY "Service role manages acquisition dead queue alerts" ON public.acquisition_dead_queue_alerts;
DROP POLICY "Service role manages acquisition daily audits" ON public.acquisition_daily_audits;
DROP POLICY "Service role manages aliases" ON public.property_aliases;
DROP POLICY "Service role manages acquisition import batches" ON public.acquisition_manual_import_batches;
DROP POLICY "Service role manages acquisition import rows" ON public.acquisition_manual_import_rows;
DROP POLICY "Service role manages acquisition source health" ON public.acquisition_source_health;
DROP POLICY service_insert_predictions ON public.market_lead_predictions;
DROP POLICY "Service role full access war_prospects" ON public.war_prospects;
DROP POLICY "Service manages onboarding sequences" ON public.onboarding_sequences;
DROP POLICY service_insert_market_leads ON public.market_leads;
DROP POLICY "Service writes safety" ON public.agent_safety_events;
DROP POLICY "Service role can manage homeowner subscriptions" ON public.homeowner_subscriptions;
DROP POLICY "Service role manages benchmarks" ON public.market_price_benchmarks;
DROP POLICY "Service role writes email_health_checks" ON public.email_health_checks;
DROP POLICY "Service manages entitlements" ON public.contractor_entitlements;
DROP POLICY "Service manages matching status" ON public.contractor_matching_status;
DROP POLICY "Service manages activation logs" ON public.admin_activation_logs;
DROP POLICY "Service role manages DNA fit results" ON public.dna_fit_results;
DROP POLICY "Service role manages source links" ON public.property_source_links;
DROP POLICY "Service role manages review items" ON public.review_items;
DROP POLICY "Service role full access states" ON public.contractor_onboarding_states;
DROP POLICY "Service role manages review insights" ON public.review_insights;
DROP POLICY "Service role can manage outreach targets" ON public.outreach_targets;
DROP POLICY "Service writes agent_runs" ON public.agent_runs;
DROP POLICY "Service writes ai_visibility_reports" ON public.ai_visibility_reports;
DROP POLICY "Service writes delivery logs" ON public.outreach_delivery_logs;
DROP POLICY "Service role full events" ON public.contractor_onboarding_events;
DROP POLICY truth_layer_topics_service_all ON public.truth_layer_article_topics;
DROP POLICY "Service role manages agent tasks" ON public.agent_tasks;
DROP POLICY "Service role manages document entities" ON public.document_entities;
DROP POLICY "Service role manages job items" ON public.ingestion_job_items;
DROP POLICY "Service role manages sniper targets" ON public.sniper_targets;
DROP POLICY "Service role can read all runtime logs" ON public.voice_runtime_logs;