// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, {
  get: (a, b) => (typeof require !== "undefined" ? require : a)[b]
}) : x)(function(x) {
  if (typeof require !== "undefined") return require.apply(this, arguments);
  throw Error('Dynamic require of "' + x + '" is not supported');
});

// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-contractors.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
function client() {
  const { createClient } = __require("npm:@supabase/supabase-js@^2.99.0");
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_contractors_default = defineTool({
  name: "search_contractors",
  title: "Search contractors",
  description: "Search UNPRO verified contractors in Qu\xE9bec by city, specialty/trade, or free-text query. Returns business name, city, specialty, AIPP score, rating and slug.",
  inputSchema: {
    query: z.string().optional().describe("Free-text search on business name."),
    city: z.string().optional().describe("City name, e.g. 'Montr\xE9al', 'Qu\xE9bec'."),
    specialty: z.string().optional().describe("Trade/specialty, e.g. 'plombier', 'toiture'."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, city, specialty, limit }) => {
    const supa = client();
    let q = supa.from("contractors").select("id, slug, business_name, specialty, city, province, aipp_score, rating, review_count, verification_status").order("aipp_score", { ascending: false, nullsFirst: false }).limit(limit ?? 10);
    if (query) q = q.ilike("business_name", `%${query}%`);
    if (city) q = q.ilike("city", `%${city}%`);
    if (specialty) q = q.ilike("specialty", `%${specialty}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: `Erreur: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { results: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-contractor.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
function client2() {
  const { createClient } = __require("npm:@supabase/supabase-js@^2.99.0");
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var get_contractor_default = defineTool2({
  name: "get_contractor",
  title: "Get contractor",
  description: "Fetch a UNPRO contractor's public profile by slug.",
  inputSchema: {
    slug: z2.string().min(1).describe("Contractor slug, e.g. 'plomberie-tremblay-montreal'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supa = client2();
    const { data, error } = await supa.from("contractors").select(
      "id, slug, business_name, legal_name, specialty, description, city, province, postal_code, website, aipp_score, rating, review_count, years_experience, rbq_number, neq, verification_status, logo_url"
    ).eq("slug", slug).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Erreur: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: `Aucun entrepreneur trouv\xE9 pour '${slug}'.` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { contractor: data }
    };
  }
});

// src/lib/mcp/tools/list-cities.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
function client3() {
  const { createClient } = __require("npm:@supabase/supabase-js@^2.99.0");
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var list_cities_default = defineTool3({
  name: "list_cities",
  title: "List Qu\xE9bec cities",
  description: "List Qu\xE9bec cities served by UNPRO. Optional prefix filter.",
  inputSchema: {
    prefix: z3.string().optional().describe("Filter cities starting with this prefix."),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ prefix, limit }) => {
    const supa = client3();
    let q = supa.from("cities").select("name, slug, region, population").order("population", { ascending: false, nullsFirst: false }).limit(limit ?? 50);
    if (prefix) q = q.ilike("name", `${prefix}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: `Erreur: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { cities: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "unpro-mcp",
  title: "UNPRO \u2014 Home Intelligence Platform",
  version: "0.1.0",
  instructions: "UNPRO is a Qu\xE9bec home intelligence platform. Use `search_contractors` to find verified contractors by city and trade, `get_contractor` for a full public profile, and `list_cities` to discover served Qu\xE9bec cities. All responses are in French (fr-CA).",
  tools: [search_contractors_default, get_contractor_default, list_cities_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
