
-- =============================================
-- SEED: Regions
-- =============================================
INSERT INTO public.jve_regions (slug, name_fr, market_type, base_cost_index) VALUES
('montreal','Montréal','mega',1.20),
('laval','Laval','large',1.12),
('monteregie','Montérégie','large',1.08),
('laurentides','Laurentides','medium',1.02),
('lanaudiere','Lanaudière','medium',1.00),
('quebec','Québec','large',1.05),
('outaouais','Outaouais','medium',1.04),
('mauricie','Mauricie','small',0.95),
('estrie','Estrie','small',0.96),
('saguenay','Saguenay–Lac-Saint-Jean','small',0.92),
('abitibi','Abitibi-Témiscamingue','small',0.90),
('bas-saint-laurent','Bas-Saint-Laurent','small',0.88),
('gaspesie','Gaspésie–Îles-de-la-Madeleine','micro',0.85),
('centre-du-quebec','Centre-du-Québec','small',0.94),
('chaudiere-appalaches','Chaudière-Appalaches','medium',0.98);

-- =============================================
-- SEED: Cities (key ones)
-- =============================================
INSERT INTO public.jve_cities (region_id, slug, name_fr, population, cost_index, competition_index, seasonality_index) VALUES
((SELECT id FROM public.jve_regions WHERE slug='montreal'),'montreal','Montréal',1800000,1.22,1.30,1.00),
((SELECT id FROM public.jve_regions WHERE slug='montreal'),'montreal-ouest','Montréal-Ouest',5200,1.18,1.15,1.00),
((SELECT id FROM public.jve_regions WHERE slug='laval'),'laval','Laval',440000,1.12,1.15,1.00),
((SELECT id FROM public.jve_regions WHERE slug='monteregie'),'longueuil','Longueuil',260000,1.08,1.10,1.00),
((SELECT id FROM public.jve_regions WHERE slug='monteregie'),'brossard','Brossard',90000,1.10,1.08,1.00),
((SELECT id FROM public.jve_regions WHERE slug='monteregie'),'boucherville','Boucherville',44000,1.10,1.05,1.00),
((SELECT id FROM public.jve_regions WHERE slug='monteregie'),'saint-hubert','Saint-Hubert',85000,1.06,1.05,1.00),
((SELECT id FROM public.jve_regions WHERE slug='lanaudiere'),'terrebonne','Terrebonne',120000,1.04,1.05,1.00),
((SELECT id FROM public.jve_regions WHERE slug='lanaudiere'),'repentigny','Repentigny',85000,1.02,1.02,1.00),
((SELECT id FROM public.jve_regions WHERE slug='laurentides'),'blainville','Blainville',60000,1.04,1.03,1.00),
((SELECT id FROM public.jve_regions WHERE slug='laurentides'),'saint-jerome','Saint-Jérôme',80000,0.98,0.95,1.00),
((SELECT id FROM public.jve_regions WHERE slug='quebec'),'quebec-ville','Québec',550000,1.06,1.08,1.00),
((SELECT id FROM public.jve_regions WHERE slug='quebec'),'levis','Lévis',150000,1.02,1.00,1.00),
((SELECT id FROM public.jve_regions WHERE slug='outaouais'),'gatineau','Gatineau',290000,1.04,1.05,1.00),
((SELECT id FROM public.jve_regions WHERE slug='estrie'),'sherbrooke','Sherbrooke',170000,0.96,0.92,1.00),
((SELECT id FROM public.jve_regions WHERE slug='mauricie'),'trois-rivieres','Trois-Rivières',140000,0.94,0.88,1.00),
((SELECT id FROM public.jve_regions WHERE slug='saguenay'),'saguenay','Saguenay',150000,0.92,0.85,1.00),
((SELECT id FROM public.jve_regions WHERE slug='monteregie'),'saint-jean-sur-richelieu','Saint-Jean-sur-Richelieu',100000,1.02,0.98,1.00),
((SELECT id FROM public.jve_regions WHERE slug='laurentides'),'mirabel','Mirabel',60000,1.02,0.95,1.00),
((SELECT id FROM public.jve_regions WHERE slug='monteregie'),'chateauguay','Châteauguay',50000,1.04,1.00,1.00);

-- =============================================
-- SEED: Trades (60+ trades)
-- =============================================
INSERT INTO public.jve_trades (slug, name_fr, name_en, category, sort_order) VALUES
('isolation','Isolation','Insulation','construction',1),
('toiture','Toiture','Roofing','construction',2),
('plomberie','Plomberie','Plumbing','construction',3),
('electricite','Électricité','Electrical','construction',4),
('chauffage','Chauffage','Heating','construction',5),
('climatisation','Climatisation','Air Conditioning','construction',6),
('thermopompe','Thermopompe','Heat Pump','construction',7),
('renovation-generale','Rénovation générale','General Renovation','construction',8),
('renovation-cuisine','Rénovation cuisine','Kitchen Renovation','construction',9),
('renovation-salle-de-bain','Rénovation salle de bain','Bathroom Renovation','construction',10),
('renovation-sous-sol','Rénovation sous-sol','Basement Renovation','construction',11),
('peinture','Peinture','Painting','construction',12),
('gypse','Gypse','Drywall','construction',13),
('planchers','Planchers','Flooring','construction',14),
('portes-fenetres','Portes et fenêtres','Doors & Windows','construction',15),
('revetement-exterieur','Revêtement extérieur','Siding','construction',16),
('excavation','Excavation','Excavation','construction',17),
('fondation','Fondation','Foundation','construction',18),
('drain-francais','Drain français','French Drain','construction',19),
('terrassement','Terrassement','Landscaping Grading','construction',20),
('pave-uni','Pavé uni','Interlock Paving','construction',21),
('paysagement','Paysagement','Landscaping','exterieur',22),
('beton','Béton','Concrete','construction',23),
('maconnerie','Maçonnerie','Masonry','construction',24),
('demolition','Démolition','Demolition','construction',25),
('nettoyage-sinistre','Nettoyage après sinistre','Post-Disaster Cleaning','services',26),
('extermination','Extermination','Pest Control','services',27),
('inspection-batiment','Inspection bâtiment','Building Inspection','professionnel',28),
('architecte','Architecte','Architect','professionnel',29),
('technologue','Technologue en architecture','Architectural Technologist','professionnel',30),
('ingenieur','Ingénieur','Engineer','professionnel',31),
('notaire','Notaire','Notary','professionnel',32),
('courtier-immobilier','Courtier immobilier','Real Estate Broker','professionnel',33),
('evaluateur-agree','Évaluateur agréé','Certified Appraiser','professionnel',34),
('avocat','Avocat','Lawyer','professionnel',35),
('arpenteur-geometre','Arpenteur-géomètre','Land Surveyor','professionnel',36),
('assurance-habitation','Assurance habitation','Home Insurance','services',37),
('gestion-copropriete','Gestion copropriété','Condo Management','services',38),
('maintenance-immeuble','Maintenance immeuble','Building Maintenance','services',39),
('alarme-securite','Alarme et sécurité','Alarm & Security','services',40),
('domotique','Domotique','Home Automation','services',41),
('vitrerie','Vitrerie','Glazing','construction',42),
('ramonage','Ramonage','Chimney Sweeping','services',43),
('decontamination','Décontamination','Decontamination','services',44),
('vermiculite','Vermiculite','Vermiculite Removal','services',45),
('desamiantage','Désamiantage','Asbestos Removal','services',46),
('gouttieres','Gouttières','Gutters','construction',47),
('soffite-fascia','Soffite et fascia','Soffit & Fascia','construction',48),
('terrasse-balcon','Terrasse et balcon','Deck & Balcony','construction',49),
('pavage-asphalte','Pavage asphalte','Asphalt Paving','construction',50),
('cloture','Clôture','Fencing','exterieur',51),
('piscine','Piscine','Pool','exterieur',52),
('spa','Spa','Spa','exterieur',53),
('toiture-plate','Toiture plate','Flat Roofing','construction',54),
('membrane-elastomere','Membrane élastomère','Elastomeric Membrane','construction',55),
('calfeutrage','Calfeutrage','Caulking','construction',56),
('restauration-degat-eau','Restauration après dégât d''eau','Water Damage Restoration','services',57),
('menuiserie','Menuiserie','Carpentry','construction',58),
('charpente','Charpente','Framing','construction',59),
('soudure','Soudure','Welding','construction',60),
('ferblanterie','Ferblanterie','Sheet Metal','construction',61);

-- =============================================
-- SEED: Trade Specialties (100+ combos)
-- =============================================
INSERT INTO public.jve_trade_specialties (trade_id, slug, name_fr) VALUES
((SELECT id FROM public.jve_trades WHERE slug='isolation'),'iso-grenier','Isolation grenier'),
((SELECT id FROM public.jve_trades WHERE slug='isolation'),'iso-entretoit','Isolation entretoit'),
((SELECT id FROM public.jve_trades WHERE slug='isolation'),'iso-insonorisation','Insonorisation'),
((SELECT id FROM public.jve_trades WHERE slug='isolation'),'iso-vide-sanitaire','Isolation vide sanitaire'),
((SELECT id FROM public.jve_trades WHERE slug='isolation'),'iso-sous-sol','Isolation sous-sol'),
((SELECT id FROM public.jve_trades WHERE slug='isolation'),'iso-urethane','Uréthane giclé'),
((SELECT id FROM public.jve_trades WHERE slug='isolation'),'iso-cellulose','Cellulose soufflée'),
((SELECT id FROM public.jve_trades WHERE slug='isolation'),'iso-laine-minerale','Laine minérale'),
((SELECT id FROM public.jve_trades WHERE slug='toiture'),'toit-bardeaux','Bardeaux asphalte'),
((SELECT id FROM public.jve_trades WHERE slug='toiture'),'toit-membrane','Membrane toiture'),
((SELECT id FROM public.jve_trades WHERE slug='toiture'),'toit-elastomere','Élastomère'),
((SELECT id FROM public.jve_trades WHERE slug='toiture'),'toit-tole','Toiture tôle'),
((SELECT id FROM public.jve_trades WHERE slug='toiture'),'toit-plate','Toiture plate'),
((SELECT id FROM public.jve_trades WHERE slug='toiture'),'toit-reparation','Réparation infiltration'),
((SELECT id FROM public.jve_trades WHERE slug='plomberie'),'plomb-residentiel','Plomberie résidentielle'),
((SELECT id FROM public.jve_trades WHERE slug='plomberie'),'plomb-urgence','Plomberie urgence'),
((SELECT id FROM public.jve_trades WHERE slug='plomberie'),'plomb-chauffe-eau','Chauffe-eau'),
((SELECT id FROM public.jve_trades WHERE slug='plomberie'),'plomb-renovation','Plomberie rénovation'),
((SELECT id FROM public.jve_trades WHERE slug='electricite'),'elec-residentiel','Électricité résidentielle'),
((SELECT id FROM public.jve_trades WHERE slug='electricite'),'elec-panneau','Changement panneau'),
((SELECT id FROM public.jve_trades WHERE slug='electricite'),'elec-urgence','Électricité urgence'),
((SELECT id FROM public.jve_trades WHERE slug='electricite'),'elec-domotique','Domotique électrique'),
((SELECT id FROM public.jve_trades WHERE slug='thermopompe'),'thermo-murale','Thermopompe murale'),
((SELECT id FROM public.jve_trades WHERE slug='thermopompe'),'thermo-centrale','Thermopompe centrale'),
((SELECT id FROM public.jve_trades WHERE slug='thermopompe'),'thermo-geothermie','Géothermie'),
((SELECT id FROM public.jve_trades WHERE slug='fondation'),'fond-fissures','Réparation fissures'),
((SELECT id FROM public.jve_trades WHERE slug='fondation'),'fond-impermeabilisation','Imperméabilisation'),
((SELECT id FROM public.jve_trades WHERE slug='fondation'),'fond-pieutage','Pieutage'),
((SELECT id FROM public.jve_trades WHERE slug='drain-francais'),'drain-installation','Installation drain'),
((SELECT id FROM public.jve_trades WHERE slug='drain-francais'),'drain-reparation','Réparation drain'),
((SELECT id FROM public.jve_trades WHERE slug='drain-francais'),'drain-inspection','Inspection par caméra'),
((SELECT id FROM public.jve_trades WHERE slug='portes-fenetres'),'pf-fenetres','Fenêtres'),
((SELECT id FROM public.jve_trades WHERE slug='portes-fenetres'),'pf-portes-entree','Portes d''entrée'),
((SELECT id FROM public.jve_trades WHERE slug='portes-fenetres'),'pf-portes-patio','Portes patio'),
((SELECT id FROM public.jve_trades WHERE slug='portes-fenetres'),'pf-portes-garage','Portes de garage'),
((SELECT id FROM public.jve_trades WHERE slug='peinture'),'peint-interieur','Peinture intérieure'),
((SELECT id FROM public.jve_trades WHERE slug='peinture'),'peint-exterieur','Peinture extérieure'),
((SELECT id FROM public.jve_trades WHERE slug='peinture'),'peint-commercial','Peinture commerciale'),
((SELECT id FROM public.jve_trades WHERE slug='planchers'),'planch-bois-franc','Bois franc'),
((SELECT id FROM public.jve_trades WHERE slug='planchers'),'planch-ceramique','Céramique'),
((SELECT id FROM public.jve_trades WHERE slug='planchers'),'planch-vinyle','Vinyle / SPC'),
((SELECT id FROM public.jve_trades WHERE slug='planchers'),'planch-sablage','Sablage et vernissage'),
((SELECT id FROM public.jve_trades WHERE slug='excavation'),'exca-terrain','Excavation terrain'),
((SELECT id FROM public.jve_trades WHERE slug='excavation'),'exca-piscine','Excavation piscine'),
((SELECT id FROM public.jve_trades WHERE slug='excavation'),'exca-drain','Excavation pour drain'),
((SELECT id FROM public.jve_trades WHERE slug='renovation-cuisine'),'cuisine-complete','Cuisine complète'),
((SELECT id FROM public.jve_trades WHERE slug='renovation-cuisine'),'cuisine-armoires','Refacing armoires'),
((SELECT id FROM public.jve_trades WHERE slug='renovation-cuisine'),'cuisine-comptoirs','Comptoirs'),
((SELECT id FROM public.jve_trades WHERE slug='renovation-salle-de-bain'),'sdb-complete','Salle de bain complète'),
((SELECT id FROM public.jve_trades WHERE slug='renovation-salle-de-bain'),'sdb-douche','Douche sur mesure'),
((SELECT id FROM public.jve_trades WHERE slug='renovation-sous-sol'),'ss-finition','Finition sous-sol'),
((SELECT id FROM public.jve_trades WHERE slug='renovation-sous-sol'),'ss-impermeabilisation','Imperméabilisation sous-sol'),
((SELECT id FROM public.jve_trades WHERE slug='revetement-exterieur'),'rev-vinyle','Revêtement vinyle'),
((SELECT id FROM public.jve_trades WHERE slug='revetement-exterieur'),'rev-canexel','Canexel'),
((SELECT id FROM public.jve_trades WHERE slug='revetement-exterieur'),'rev-brique','Brique'),
((SELECT id FROM public.jve_trades WHERE slug='revetement-exterieur'),'rev-pierre','Pierre'),
((SELECT id FROM public.jve_trades WHERE slug='maconnerie'),'macon-brique','Maçonnerie brique'),
((SELECT id FROM public.jve_trades WHERE slug='maconnerie'),'macon-pierre','Maçonnerie pierre'),
((SELECT id FROM public.jve_trades WHERE slug='maconnerie'),'macon-joints','Rejointoiement'),
((SELECT id FROM public.jve_trades WHERE slug='chauffage'),'chauff-fournaise','Fournaise'),
((SELECT id FROM public.jve_trades WHERE slug='chauffage'),'chauff-plancher-radiant','Plancher radiant'),
((SELECT id FROM public.jve_trades WHERE slug='chauffage'),'chauff-foyer','Foyer'),
((SELECT id FROM public.jve_trades WHERE slug='climatisation'),'clim-central','Climatisation centrale'),
((SELECT id FROM public.jve_trades WHERE slug='climatisation'),'clim-mural','Climatiseur mural'),
((SELECT id FROM public.jve_trades WHERE slug='piscine'),'pisc-creusee','Piscine creusée'),
((SELECT id FROM public.jve_trades WHERE slug='piscine'),'pisc-hors-terre','Piscine hors terre'),
((SELECT id FROM public.jve_trades WHERE slug='piscine'),'pisc-entretien','Entretien piscine'),
((SELECT id FROM public.jve_trades WHERE slug='beton'),'beton-dalle','Dalle de béton'),
((SELECT id FROM public.jve_trades WHERE slug='beton'),'beton-escalier','Escalier béton'),
((SELECT id FROM public.jve_trades WHERE slug='beton'),'beton-reparation','Réparation béton'),
((SELECT id FROM public.jve_trades WHERE slug='terrasse-balcon'),'terrasse-bois','Terrasse bois'),
((SELECT id FROM public.jve_trades WHERE slug='terrasse-balcon'),'terrasse-composite','Terrasse composite'),
((SELECT id FROM public.jve_trades WHERE slug='terrasse-balcon'),'balcon-fibre','Balcon fibre de verre');
